# App
spring.application.name=railway-transfer-portal
server.port=8080

# Local MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/railway_transfer_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=BpRYMsEa1Pf6qJ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=railway_super_secret_key_change_this_in_production
jwt.expiration=86400000

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_GMAIL
spring.mail.password=YOUR_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000